import { Ubuntu } from "next/font/google";
import "./globals.css";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-ubuntu",
  display: "swap",
});

export const metadata = {
  title: "Multi step form",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.variable} antialiased `}
        style={{ backgroundColor: "hsl(218, 100%, 97%)" }}
      >
        <main className="flex items-center justify-center md:min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
